set_project("charmap")
set_version("0.4.0")
set_license("MIT")
add_rules("mode.debug", "mode.release")
add_cxxflags("/utf-8")

target("charmap")
    add_rules("qt.widgetapp")
    add_files("*.cpp")
    add_files("*.h")


includes("@builtin/xpack")
xpack("charmap")
    set_formats("zip")
    set_title("Charmap")
    set_author("ChenQingYu")
    set_description("A quick Unicode characters lookup table.")
    set_homepage("https://github.com/chen-qingyu/charmap")
    set_bindir("/")
    add_targets("charmap")
    add_installfiles("README.md")
    local qt_path = "C:/Qt/6.8.1/msvc2022_64"
    add_installfiles(qt_path .. "/bin/Qt6Core.dll", qt_path .. "/bin/Qt6Gui.dll",  qt_path .. "/bin/Qt6Widgets.dll")
    add_installfiles(qt_path .. "/plugins/platforms/qwindows.dll", {prefixdir = "platforms/"})
    add_installfiles(qt_path .. "/plugins/styles/qmodernwindowsstyle.dll", {prefixdir = "styles/"})
